# Generated by Django 4.0.1 on 2022-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
